### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by nSedrickm** [Afkanerd/afkanerd.github.io#1]
Hey Sherlock .Do you need some help on this ? .I can do a thing or two.

**Comment by Wisdom-Nji** [comment]
Hey boy, sure!! Could use some help adding awesome features to it (also they're some typos just lying around haha). Let me know what you've got in mind

**Comment by nSedrickm** [comment]
Copy. Will do so .

**Comment by nSedrickm** [comment]
Copy will do .

**Comment by nSedrickm** [comment]
Any specific reason for using the dark theme?

**Comment by Wisdom-Nji** [comment]
it's easier to read without producing eye strain

**Comment by nSedrickm** [comment]
Ok
